baseURL = "https://shane.ai/"
languageCode = "en-us"
title = "Words from Shane"


[params]
author="shane"
themeColor = "pink"
contentTypeName = "posts"


[author]
name="shane"

[module]
[[module.imports]]
path = 'github.com/panr/hugo-theme-terminal'

[languages]
  [languages.en]
    [languages.en.params.logo]
      logoText = "Shane.ai"
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"